# SPDX-FileCopyrightText: 2024 Shahryar Tavakkoli
# SPDX-FileCopyrightText: 2024 igniter_js contributors <https://github.com/ash-project/igniter_js/graphs.contributors>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: mix
    versioning-strategy: lockfile-only
    directory: "/"
    ignore:
      - dependency-name: "rustler"
    schedule:
      interval: weekly
      day: thursday
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
