[package]
name = "igniter_js"
version = "0.2.0"
authors = ["Shahryar Tavakkoli"]
edition = "2021"

[lib]
name = "igniter_js"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
oxc = { version = "0.44.0", features = ["codegen"] }
rustler = { version = "0.35.1" }
