[package]
name = "igniter_js"
version = "0.4.3"
authors = ["Shahryar Tavakkoli"]
edition = "2021"

[lib]
name = "igniter_js"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
swc_common = { version = "5.0.0", features = ["tty-emitter"] }
swc_ecma_parser = { version = "6.0.2" }
swc_ecma_visit = "5.0.0"
swc_ecma_ast = "5.0.1"
swc_ecma_codegen = "5.0.1"
rustler = "=0.35.1"
