# SPDX-FileCopyrightText: 2024 Shahryar Tavakkoli
# SPDX-FileCopyrightText: 2024 igniter_js contributors <https://github.com/ash-project/igniter_js/graphs.contributors>
#
# SPDX-License-Identifier: MIT

name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    with:
      spark-formatter: false
      spark-cheat-sheets: false
      sobelow: false
      igniter-upgrade: false
      rustler-precompiled-module: IgniterJs.Native
      reuse: true
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
